--
-- Author: ffl
-- Date: 2015-07-02 13:58:41
--
EVENT_SCORE_CHANGE = "EVENT_SCORE_CHANGE" --回合分数改变
EVENT_PAUSE = "EVENT_PAUSE" --游戏暂停
EVENT_CONTINUE = "EVENT_CONTINUE" --游戏继续

EVENT_SOUND_TOGGLE_CHANGE = "EVENT_SOUND_TOGGLE_CHANGE"
EVENT_MUSIC_TOGGLE_CHANGE = "EVENT_MUSIC_TOGGLE_CHANGE"